import '../../../core/l10n/app_strings.dart';

/// Support bot used by all feedback flows.
const String kTelegramUrl = 'https://t.me/kopri_support_bot';

/// Flag emoji per translation language code (picker tiles).
String langFlagFor(String code) => switch (code) {
  'auto' => '🌐',
  'az' => '🇦🇿',
  'af' => '🇿🇦',
  'sq' => '🇦🇱',
  'am' => '🇪🇹',
  'en' => '🇬🇧',
  'ar' => '🇸🇦',
  'hy' => '🇦🇲',
  'eu' => '🇪🇸',
  'be' => '🇧🇾',
  'bn' => '🇧🇩',
  'my' => '🇲🇲',
  'bg' => '🇧🇬',
  'bs' => '🇧🇦',
  'cy' => '🇬🇧',
  'hu' => '🇭🇺',
  'vi' => '🇻🇳',
  'gl' => '🇪🇸',
  'el' => '🇬🇷',
  'ka' => '🇬🇪',
  'gu' => '🇮🇳',
  'da' => '🇩🇰',
  'zu' => '🇿🇦',
  'he' => '🇮🇱',
  'id' => '🇮🇩',
  'ga' => '🇮🇪',
  'is' => '🇮🇸',
  'es' => '🇪🇸',
  'it' => '🇮🇹',
  'yo' => '🇳🇬',
  'kk' => '🇰🇿',
  'kn' => '🇮🇳',
  'ca' => '🇰🇸',
  'ky' => '🇰🇬',
  'zh' => '🇨🇳',
  'ko' => '🇰🇷',
  'km' => '🇰',
  'lo' => '🇱🇦',
  'la' => '🇻',
  'lv' => '🇱🇻',
  'lt' => '🇱🇹',
  'mk' => '🇲',
  'ms' => '🇲🇾',
  'ml' => '🇮🇳',
  'mt' => '🇲',
  'mr' => '🇮🇳',
  'mn' => '🇲🇳',
  'ne' => '🇳',
  'nl' => '🇳🇱',
  'no' => '🇳🇴',
  'pa' => '🇵🇰',
  'fa' => '🇮🇷',
  'pl' => '🇵🇱',
  'pt' => '🇵🇹',
  'ro' => '🇷🇴',
  'ru' => '🇷🇺',
  'sr' => '🇷🇸',
  'si' => '🇱',
  'sk' => '🇸🇰',
  'sl' => '🇸',
  'sw' => '🇰',
  'tg' => '🇹',
  'th' => '🇹🇭',
  'ta' => '🇮',
  'te' => '🇮🇳',
  'tr' => '🇹🇷',
  'tk' => '🇹🇲',
  'uz' => '🇺🇿',
  'uk' => '🇺',
  'ur' => '🇵🇰',
  'fi' => '🇫',
  'fr' => '🇫🇷',
  'hi' => '🇮🇳',
  'hr' => '🇭',
  'cs' => '🇨🇿',
  'sv' => '🇸🇪',
  'et' => '🇪🇪',
  'ja' => '🇯',
  _ => '',
};

/// Sample phrase used by the TTS preview tile.
String ttsExampleFor(AppLang lang) => switch (lang) {
  AppLang.ru => 'Привет, как дела?',
  AppLang.tk => 'Salam, ýagdaýyňyz nähili?',
  AppLang.en => 'Hello, how are you?',
  AppLang.tr => 'Merhaba, nasılsınız?',
};
